version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echo_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/echo
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  mongodb:
    image: mongo:7
    container_name: echo_mongodb
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: echo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: